/*
 * This source file was generated by the Gradle 'init' task
 */
package com.jasper.compiler;

import net.sf.jasperreports.engine.JasperCompileManager;

import java.io.File;

public class App {

    public static void main(String[] args) {

        // Check if a file name was provided as a command-line argument
        if (args.length == 0) {
            System.out.println("Usage: jaspereport-compiler.jar <file-name>");
            return;
        }

        // Get the file name from the command-line argument
        String fileName = args[0];

        final var file = new File(fileName);
        final var filePath = file.getAbsolutePath();
        final var compiledFilePath = String.format("%s.jasper", filePath);


        System.out.println("Compiling file: " + filePath);

        try {
            JasperCompileManager.compileReportToFile(filePath, compiledFilePath);
            System.out.println("--- compiled to: " + compiledFilePath);
        } catch (Throwable throwable) {
            System.out.println("Error compiling: " + throwable.getMessage());
            throwable.printStackTrace();
        }

    }
}
